#!/bin/bash

#SBATCH --job-name-habit-tracker-hpc #Job name
#SBATCH --time=00:05:00 # run time
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=128M
#SBATCH --output=habit_output.txt
#SBATCH --error=habit_error.txt
module purge
module load StdEnv2023
module load python/3.11.5

if [ ! -d "myenv" ]; then
python 3 -m venv myenv
fi
source myenv/bin/activate

pip install --upgrade pip
pip install asteval

python/home/damindra96/project-hpc-dgalbokkah.py
